project:
  type: website

website:

  title: "Análisis Descriptivo ENPOL 2021"
  sidebar:
      logo: images/LogoUnal.png
      title: "Análisis Descriptivo ENPOL 2021"
      style: "docked"
      search: true
      contents:
        - href: ResumenIntro.qmd
          text: Resumen
        - section: "Marco conceptual"
          contents:
            - href: Antecedentes.qmd
              text: Marco de antecedentes
            - href: index.qmd
              text: Objetivos y justificación
            - href: Datos.qmd
              text: Descripción de los datos
        - section: "Análisis descriptivo"
          contents:
            - href: dashboard.qmd
              text: Análisis descriptivo univariado
            - href: PCA.qmd
              text: Análisis de Componentes Principales (PCA)
        - href: about.qmd
          text: Sobre nosotros
          
format:
  html:
    theme: 
      light: simplex
      dark: slate
    css: styles.css
    toc: true
    toc-expand: 2
    toc-title: "Tabla de contenidos"
    toc-location: right

editor: visual
lang: es
