---
title: "Conclusiones"
author: "Juan Pablo Montaño Díaz & Laura Katherine Martinez Castiblanco"
format: html
editor: source
---

A lo largo de este proyecto se emplearon diferentes métodos de análisis descriptivos en los datos obtenidos por la Encuesta Nacional de la Población Privada de la Libertad 2021 (ENPOL). El uso de estos métodos respondía al propósito descriptivo del estudio, el cual pretendía encontrar relaciones entre las condiciones de vida y características sociodemográficas,delictivas y económicas de las personas privadas de la libertad dentro de los centro penitenciarios de los Estados Unidos Mexicanos.

# Sobre el objetivo

Se observó que las condiciones de vida dentro del centro penitenciario están principalmente relacionadas entre sí, lo que sugiere que dichas condiciones poseen un alto grado de independencia de las características individuales y reflejan, en su mayoría, factores inherentes a los propios centros penitenciarios. Sin embargo, a través del Análisis de Correspondencias Múltiples y el agrupamiento de las variables, se evidenció que las condiciones de la vida intracarcelaria varían según el sexo, el estado judicial (procesado o condenado), el motivo de detención, la presencia de alguna discapacidad en la persona, el tipo de cárcel donde está recluida la persona, entre otras variables.

Por lo tanto, este estudio nos muestra la existecia de relaciones significativas entre las condiciones de vida intracarcelaria y algunas características individuales en la población estudiada. Algunas de estas conclusiones son coherentes con la literatura existente y pueden parecer evidentes. Por ejemplo, es coherente que las condiciones de vida intracarcelaria difieran según el sexo, ya que las cárceles femeninas, al tener menor cantidad de reclusas, posean un menor hacinamiento en comparación con los centros penitenciarios masculinos.

En conclusión, se considera que este estudio proporciona información valiosa y significativa para describir adecuadamente la población estudiada, permitiendo identificar patrones y caracterizar a los individuos con base en estos.


# Resultados generales

El análisis descriptivo y exploratorio realizado en este proyecto reveló hallazgos adicionales que no se encuentran directamente relacionados con los objetivos del estudio. Por ejemplo, se observó una relación entre el sexo del individuo, la edad de inicio en el consumo de drogas y el motivo por el cual la persona paró sus estudios. También, se identificó una fuerte correlación entre las variables de expectativas de salida, además de una fuerte relación entre las condiciones económicas y el último salario recibido antes de la detención.

Estos resultados nos sugieren que la base de datos utilizada aún contiene una gran cantidad de información útil y significativa que podría explorarse en mayor profundidad al modificarse el enfoque y los objetivos del análisis. Recordemos que la base de datos original cuenta con aproximadamente 500 variables, y aunque muchas de ellas no eran adecuadas para los objetivos de este proyecto, es muy probable que puedan darnos más resultados inesperados sobre la población privada de libertad.